export const products = [
  {
    id: 1,
    src: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    price: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "shoes",
  },
  {
    id: 2,
    src: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    price: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "shoes",
  },
  {
    id: 3,
    src: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    price: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "shoes",
  },
  {
    id: 4,
    src: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    price: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "shoes",
  },
  {
    id: 5,
    src: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    price: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "shoes",
  },
];
